class AlreadyAcquiredError(Exception):
    pass


class AlreadyExistsError(KeyError):
    pass
